language: c # or other C/C++ variants

sudo: false

# https://docs.travis-ci.com/user/caching/
#
# Caching the whole nim folder is better than relying on ccache - this way, we
# skip the expensive bootstrap process and linking
cache:
  directories:
    - nim

os:
  - linux
  - osx

install:
  - mkdir external
  - wget -q https://www.lua.org/ftp/lua-5.3.5.tar.gz
  - tar xfz lua-5.3.5.tar.gz -C external
  - mv external/lua-5.3.5 external/lua

  # build nim from our own branch - this to avoid the day-to-day churn and
  # regressions of the fast-paced Nim development while maintaining the
  # flexibility to apply patches
  #
  # check version of remote branch
  - "export NIMVER=$(git ls-remote https://github.com/nim-lang/nim.git HEAD | cut -f 1)"

  # after building nim, wipe csources to save on cache space
  - "{ [ -f nim/$NIMVER/bin/nim ] && [ -f nim/$NIMVER/bin/nimble ] ; } ||
      { rm -rf nim ;
        mkdir -p nim ;
        git clone --depth=1 https://github.com/nim-lang/nim.git nim/$NIMVER ;
        cd nim/$NIMVER ;
        sh build_all.sh > /dev/null;
        rm -rf csources ;
        cd ../.. ;
      }"
  - "export PATH=$PWD/nim/$NIMVER/bin:$PATH"

script:
  - nim e scripts/build_static_lib.nims
  - nimble test
